# Introduction

This is a book created from markdown and executable code.

See @knuth84 for additional discussion of literate programming.




## General Information

| DESCRIPTION   | VALUE                                                                |
|---------------|----------------------------------------------------------------------|
| Module Name   | MECH-M-3-IEL-IEL-ILV                                                 |
| Semester      | 3                                                                    |
| Assessment(s) | One (1) final exam worth 3/6 and three (3) exercises worth 1/6 each. |
| SWS Total     | 2                                                                    |
| Total Units   | 30                                                                   |
| ECTS          | 3                                                                    |
| Type          | ILV                                                                  |

> [!IMPORTANT]
> Re-examinations take place in oral form, unless otherwise specified.

---

## Structure

| MEETING | UE  | TYPE                             | TOPICS                               |
|---------|-----|----------------------------------|--------------------------------------|
| 1       | 2UE | (ILV)                            | Isolated converters and applications |
| 2       | 2UE | Self-study (ILV)                 | Isolated converters and applications |
| 3       | 2UE | (ILV)                            | Isolated converters and applications |
| 4       | 4UE | (ILV)                            | Isolated converters and applications |
| 5       | 2UE | Self-study work  (ILV)           | Isolated converters and applications |
| 6       | 6UE | Gastvortrag Würth Elektronik EMC | -                                    |
| 7       | 2UE | (ILV)                            | EMC compliant PCB design             |
| 8       | 2UE | Self-study work  (ILV)           | EMC                                  |
| 9       | 2UE | (ILV)                            | EMC                                  |
| 10      | 2UE | (ILV)                            | EMC                                  |
| 11      | 2UE | (ILV)                            | EMC                                  |
| 12      | 2UE | (ILV)                            | EMC                                  |
| 13      | 2UE | Exam                             | Final Exam                           |

> [!IMPORTANT]
> The exact schedule may change at any time during the semester.

## Reading List
| TITLE | AUTHOR | PUBLISHER |
|----|----|----|
